#!/usr/bin/env python3
"""Stub asset headers for COS_RUNTIME_ASSETS builds (docs/RUNTIME_ASSETS.md, "Proposal" step 1).

    native/tools/gen_asset_stubs.py --decomp build/decomp --out DIR

The game includes 163 "assets/*.h" headers that the decompilation's asset step cuts out of the
player's main.dol and RELs (gen_assets.sh). This writes headers with the same names, declarations,
sizes and alignment but no contents, from the decompilation's config.yml and symbols.txt only (no
disc): each array is filled from the disc when the program starts (native/src/pc/pc_assets.cpp).

DIR/include/assets/<name>.h       one stub per asset, the declaration the real header makes
                                  (static or not, the element type, the alignment; a matDL header
                                  stays a macro taking the texture name)
DIR/include/assets/cos_assets.h   COS_ASSET_FILL, the call that registers or fills an array
DIR/include/assets/cos_asset_table.inc
                                  one row per asset for the loader: where its bytes are (main.dol
                                  address, or REL section and offset), size, element type, and the
                                  SHA-1 the decompilation records for that main.dol or REL
DIR/include/assets/cos_asset_index.json
                                  row number -> header name, for native/tools/check_runtime_assets.py

Nothing here is derived from the disc: names, addresses, sizes and hashes come from the
decompilation's committed config (symbols.txt is CC0). The res/ enum headers are copied by
gen_assets.sh --res-only, not here.
"""
import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("gen_asset_stubs: needs PyYAML (pip install pyyaml), as the decompilation's configure.py")

# element types: their size and the loader's conversion (pc_assets.h CosAssetKind)
KINDS = {
    None: ("unsigned char", 1, "COS_ASSET_RAW"),
    "matDL": ("u8", 1, "COS_ASSET_RAW"),
    "Vec": ("Vec", 12, "COS_ASSET_F32"),
    "cXy": ("cXy", 8, "COS_ASSET_F32"),
    "GXColor": ("GXColor", 4, "COS_ASSET_RAW"),
}
TYPE_INCLUDES = {
    "Vec": '#include "dolphin/mtx/vec.h"\n',
    "cXy": '#include "SSystem/SComponent/c_xyz.h"\n',
    "GXColor": '#include "dolphin/gx/GXStruct.h"\n',
}
SYMBOL_RE = re.compile(r"^(\S+) = (\S+):0x([0-9A-Fa-f]+); // (.*)$")

# dtk's raw headers define ATTRIBUTE_ALIGN themselves
ALIGN_BLOCK = """#ifndef ATTRIBUTE_ALIGN
#if defined(__MWERKS__) || defined(__GNUC__)
#define ATTRIBUTE_ALIGN(num) __attribute__((aligned(num)))
#elif defined(_MSC_VER) || defined(__INTELLISENSE__)
#define ATTRIBUTE_ALIGN(num)
#else
#error unknown compiler
#endif
#endif
"""

# matDL_dis.py's headers define the display-list macros for the units that include them
MATDL_BLOCK = """#ifndef LOAD_BP_REG
#define U32_AS_U8(v) (((v) >> 24) & 0xFF), (((v) >> 16) & 0xFF), (((v) >> 8) & 0xFF), (((v) >> 0) & 0xFF)
#define U24_AS_U8(v) (((v) >> 16) & 0xFF), (((v) >> 8) & 0xFF), (((v) >> 0) & 0xFF)
#define U16_AS_U8(v) (((v) >> 8) & 0xFF), (((v) >> 0) & 0xFF)
#define IMAGE_ADDR(addr) (u32)(addr) >> 5
#define LOAD_BP_REG(reg, value) GX_CMD_LOAD_BP_REG, reg, U24_AS_U8(value)
#define LOAD_XF_REG(reg, num_args, ...) GX_CMD_LOAD_XF_REG, U16_AS_U8(num_args-1), U16_AS_U8(reg), __VA_ARGS__
#define LOAD_CP_REG(reg, value) GX_CMD_LOAD_CP_REG, reg, U32_AS_U8(value)
#endif
"""

COS_ASSETS_H = """// Generated by native/tools/gen_asset_stubs.py (COS_RUNTIME_ASSETS): no game data.
#ifndef COS_ASSETS_H
#define COS_ASSETS_H
// cos_asset_fill (declared in native/include/pc/cos_pc_config.h, which every game unit includes
// first; native/src/pc/runtime/pc_assets.cpp): before the loader has read the disc, records the
// array; after, copies its bytes in at once (an array in a function body registers on the
// function's first call)
#define COS_ASSET_FILL(sym, id) \\
    [[maybe_unused]] static const bool sym##__cos_asset_filled = cos_asset_fill((void*)(sym), sizeof(sym), (id))
#endif
"""


def read_symbols(path):
    by_name, by_addr = {}, {}
    for line in Path(path).read_text().splitlines():
        m = SYMBOL_RE.match(line.strip())
        if not m:
            continue
        name, section, addr, attrs = m.group(1), m.group(2), int(m.group(3), 16), m.group(4)
        fields = dict(a.split(":", 1) for a in attrs.split() if ":" in a)
        row = {"name": name, "section": section, "addr": addr, "size": int(fields.get("size", "0"), 16),
               "scope": fields.get("scope", "global"), "align": int(fields.get("align", "4"))}
        by_name.setdefault(name, []).append(row)
        by_addr[(section, addr)] = row
    return by_name, by_addr


def section_order(splits):
    names = []
    for line in Path(splits).read_text().splitlines():
        if line.startswith("Sections:"):
            continue
        if not line.startswith("\t"):
            if names:
                break
            continue
        names.append(line.split()[0])
    return names


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--decomp", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()
    d = args.decomp
    cfg = yaml.safe_load((d / "config/GZLE01/config.yml").read_text())

    modules = [{"object": cfg["object"], "hash": cfg["hash"], "symbols": cfg["symbols"],
                "splits": cfg["splits"], "extract": cfg.get("extract") or []}]
    modules += [m for m in cfg["modules"] if m.get("extract")]

    out = args.out / "include" / "assets"
    out.mkdir(parents=True, exist_ok=True)
    (out / "cos_assets.h").write_text(COS_ASSETS_H)
    rows = []
    index = []  # cos_asset_index.json: id -> header, for native/tools/check_runtime_assets.py
    for mod in modules:
        obj = mod["object"]
        is_dol = obj == "sys/main.dol"
        # disc paths: "/rels/x.rel", or "/RELS.arc" plus the file inside it
        if is_dol:
            disc_file, arc_file = "", ""
        else:
            path = obj[len("files"):]
            disc_file, _, arc_file = path.partition(":")
        by_name, by_addr = read_symbols(d / mod["symbols"])
        order = section_order(d / mod["splits"])
        for e in mod["extract"]:
            sym = e["symbol"]
            if "!" in sym:  # "name!.section:0xADDR", for names that are not unique
                name, _, loc = sym.partition("!")
                section, _, addr = loc.partition(":")
                row = by_addr.get((section, int(addr, 16)))
            else:
                name = sym
                found = by_name.get(name, [])
                row = found[0] if len(found) == 1 else None
            if row is None:
                sys.exit(f"gen_asset_stubs: {obj}: symbol {sym} not found once in {mod['symbols']}")
            name = e.get("rename") or name
            ctype = e.get("custom_type")
            elem, esize, kind = KINDS[ctype]
            size = row["size"]
            if size == 0 or size % esize:
                sys.exit(f"gen_asset_stubs: {sym}: size {size:#x} is not a whole number of {elem}")
            scope = (e.get("custom_data") or {}).get("scope", "local") if ctype else row["scope"]
            header = Path(e["header"]).name
            rid = len(rows)
            if is_dol:
                where, sec, off = f"main.dol {row['section']} {row['addr']:#x}", 0, row["addr"]
            else:
                sec = order.index(row["section"]) + 1  # REL section 0 is the null section
                where, off = f"{obj[len('files/'):]} {row['section']} (section {sec}) +{row['addr']:#x}", row["addr"]
            rows.append((name, disc_file, arc_file, sec, off, size, kind, mod["hash"]))
            index.append({"id": rid, "name": name, "header": header, "kind": kind, "size": size})

            text = "// Generated by native/tools/gen_asset_stubs.py (COS_RUNTIME_ASSETS): no game data.\n"
            text += f"// {name}: {where}, {size:#x} bytes, filled from the disc at start-up\n"
            text += '#include "assets/cos_assets.h"\n'
            static = "static " if scope == "local" or row["section"] in (".rodata", ".sdata2") else ""
            count = f"{size // esize:#x}"
            if ctype == "matDL":
                text += MATDL_BLOCK
                macro = Path(e["header"]).stem
                text += f"\n#define {macro}(TEX_NAME) \\\n"
                text += f"{static}u8 {name}[{count}] ALIGN_DECL(32); \\\n"
                text += f"COS_ASSET_FILL({name}, {rid});\n"
            elif ctype is None:
                text += ALIGN_BLOCK
                text += f"{static}unsigned char {name}[{count}] ATTRIBUTE_ALIGN({row['align']});\n"
                text += f"COS_ASSET_FILL({name}, {rid});\n"
            else:
                text += TYPE_INCLUDES[ctype]
                text += f"\n{static}{elem} {name}[{count}];\n"
                text += f"COS_ASSET_FILL({name}, {rid});\n"
            (out / header).write_text(text)

    table = ["// Generated by native/tools/gen_asset_stubs.py: where each asset is on the disc (no game data).",
             "// name, disc file (empty: main.dol), file inside that RARC, REL section (0: a main.dol address),",
             "// offset or address, size, element type, SHA-1 of the decompressed main.dol or REL"]
    for name, disc_file, arc_file, sec, off, size, kind, sha in rows:
        table.append(f'COS_ASSET_ROW("{name}", "{disc_file}", "{arc_file}", {sec}, {off:#x}, {size:#x}, {kind}, "{sha}")')
    (out / "cos_asset_table.inc").write_text("\n".join(table) + "\n")
    (out / "cos_asset_index.json").write_text(json.dumps(index, indent=1) + "\n")
    print(f"gen_asset_stubs: {len(rows)} stub headers in {out}")


if __name__ == "__main__":
    main()
