//
// Generated by dtk
// Translation Unit: c_API_graphic.cpp
//

#include "SSystem/SComponent/c_API_graphic.h"
#include "SSystem/SComponent/c_API.h"
#include "dolphin/types.h"
#if TARGET_PC
#include "pc/pc_harness.h"
#include "pc/game_hooks.h"
#endif

/* 8024135C-8024138C       .text cAPIGph_Painter__Fv */
void cAPIGph_Painter(void) {
#if TARGET_PC
    // Step 6.7 (pc_frame.cpp): mDoGph_Painter's GX encode, a phase of COS_PERF / COS_PERF_EVERY
    // (COS_FPS60_TEST's paint B apart).
    const int phase = pc_paint_is_extra() ? PC_PERF_PAINTER2 : PC_PERF_PAINTER;
    pc_perf_begin(phase);
    g_cAPI_Interface.mpPainter();
    pc_perf_end(phase);
#else
    g_cAPI_Interface.mpPainter();
#endif
}

/* 8024138C-802413BC       .text cAPIGph_BeforeOfDraw__Fv */
void cAPIGph_BeforeOfDraw(void) {
    g_cAPI_Interface.mpBeforeOfDraw();
}

/* 802413BC-802413EC       .text cAPIGph_AfterOfDraw__Fv */
void cAPIGph_AfterOfDraw(void) {
    g_cAPI_Interface.mpAfterOfDraw();
}
